# -*- coding: utf-8 -*-
"""CodeAlpha_StockPortfolioTracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygBd8bQRSn_dmwpyz1QrjIpw6Rs7W982
"""

# ==============================
# STOCK PORTFOLIO TRACKER
# ==============================

# Predefined stock prices
stock_prices = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOG": 140,
    "MSFT": 420,
    "AMZN": 190,
    "META": 500
}

portfolio = {}
total_investment = 0

print("================================")
print("     STOCK PORTFOLIO TRACKER")
print("================================")

print("\nAvailable Stocks:")
for stock, price in stock_prices.items():
    print(stock, "=", "$", price)

# Ask how many different stocks
number_of_stocks = int(input("\nHow many different stocks do you own? "))

# Take stock details
for i in range(number_of_stocks):

    print("\nStock", i + 1)

    stock_name = input("Enter stock name: ").upper()

    # Check whether stock is available
    if stock_name not in stock_prices:
        print("❌ Stock not available.")
        continue

    quantity = int(input("Enter quantity: "))

    # Calculate value
    price = stock_prices[stock_name]
    value = price * quantity

    portfolio[stock_name] = {
        "quantity": quantity,
        "price": price,
        "value": value
    }

    total_investment += value

# ==============================
# PORTFOLIO SUMMARY
# ==============================

print("\n================================")
print("       PORTFOLIO SUMMARY")
print("================================")

if len(portfolio) == 0:
    print("No stocks were added.")

else:
    for stock, details in portfolio.items():

        print("\nStock:", stock)
        print("Quantity:", details["quantity"])
        print("Price per share: $", details["price"])
        print("Total value: $", details["value"])

print("\n--------------------------------")
print("Total Investment: $", total_investment)
print("--------------------------------")

# ==============================
# SAVE TO TEXT FILE
# ==============================

save = input("\nDo you want to save the portfolio? (yes/no): ").lower()

if save == "yes":

    with open("portfolio.txt", "w") as file:

        file.write("STOCK PORTFOLIO TRACKER\n")
        file.write("=======================\n\n")

        for stock, details in portfolio.items():

            file.write("Stock: " + stock + "\n")
            file.write("Quantity: " + str(details["quantity"]) + "\n")
            file.write("Price: $" + str(details["price"]) + "\n")
            file.write("Value: $" + str(details["value"]) + "\n\n")

        file.write("-----------------------\n")
        file.write("Total Investment: $" + str(total_investment))

    print("✅ Portfolio saved successfully as portfolio.txt")

else:
    print("Portfolio was not saved.")

print("\nThank you for using Stock Portfolio Tracker! 😊")